version: '3.7'

services:
    php-httpd:
        image: php:7.3-apache
        ports:
            - 80:80
        volumes:
            - "./DocumentRoot:/var/www/html"
        networks:
            - backend

    mysql_db_container:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_PASSWORD: 'testpassword'
          MYSQL_DATABASE: 'testdb'
        ports:
            - 3306:3306
        volumes:
            - mysql_db_data_container:/var/lib/mysql
        networks:
            - backend

     phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - 'mysql_db_container:db'
        ports:
            - 6001:80
        networks:
            - backend
              
      nginx_web:
         image: nginx:latest
         volumes:
              - ./templates:/etc/nginx/templates
         ports:
              - "6666:80"
          environment:
              - NGINX_HOST=index.php
              - NGINX_PORT=6666
          networks:
              - backend
              - frontend
    
volumes:
  mysql_db_data_container:
  
networks:
  - backend:
  - frontend:
